# TODO: try to make this scale automatically based on display size
SCALE = 2

# The size of a single grid cell
GRID_CELL_HEIGHT = 16 * SCALE
GRID_CELL_WIDTH = 9 * SCALE

# game grid
GAME_GRID_ROWS = 23
GAME_GRID_COLS = 64

GAME_GRID_HEIGHT = GAME_GRID_ROWS * GRID_CELL_HEIGHT
GAME_GRID_WIDTH = GAME_GRID_COLS * GRID_CELL_WIDTH

# scoreboard grid
SCOREBOARD_GRID_ROWS = 25
SCOREBOARD_GRID_COLS = 14

# Total dimensions of the window
SCREEN_GRID_ROWS = 25
SCREEN_GRID_COLS = 80

# Total size of the window
WINDOW_HEIGHT = SCREEN_GRID_ROWS * GRID_CELL_HEIGHT
WINDOW_WIDTH = SCREEN_GRID_COLS * GRID_CELL_WIDTH
