from random import randint
from constants import BLACK, BLUE, BROWN, COLORS, LIGHTBLUE, LIGHTCYAN, LIGHTGRAY, LIGHTGREEN, LIGHTRED, RED, SCREEN_GRID_COLS, WHITE, YELLOW, SCREEN_GRID_ROWS
from renderer.cell_grid import CellGrid


def original_kroz_trilogy(g: CellGrid):
    g.fill = BLUE
    g.bak(BLUE, BLACK);#bor(4)
    g.clrscr();g.cur(3)
    g.gotoxy(32,1)
    g.col(RED,LIGHTGRAY);g.bak(BLUE,BLACK)
    g.write('ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ')
    g.gotoxy(32,3)
    g.write('ßßßßßßßßßßßßßßßß')
    g.gotoxy(25,5);g.col(WHITE, WHITE)
    g.write('An Apogee Software Production')
    g.gotoxy(28,7)
    g.write('Created by Scott Miller')
    g.gotoxy(1,9);g.col(LIGHTCYAN,LIGHTGRAY)
    g.writeln('  In your search for the precious Crown within the mysterious kingdom of Kroz')
    g.writeln('  you have blundered upon a secret passage leading deep into the Earth.  With')
    g.writeln('  your worn lantern you journey downward void of fear,  sweat beading on your')
    g.writeln('  forehead as you anticipate great treasures.  Undoubtedly, the Crown must be')
    g.writeln('  guarded by unspeakable dangers.  Still, armed with a whip and great courage')
    g.writeln('           you decide to continue your quest, and journey downward...')
    g.gotoxy(1,17);g.col(LIGHTGREEN,LIGHTGRAY)
    g.write('         Use the cursor keys to move yourself (')
    g.col(YELLOW, WHITE);g.write(chr(2));g.col(LIGHTGREEN,LIGHTGRAY)
    g.writeln(') through the kingdom.')
    g.writeln('            Use your whip (press W) to destroy all nearby creatures.')
    g.writeln('       You are on your own to discover what other mysteries await--some')
    g.writeln('                           helpful, others deadly...')
    g.col(YELLOW,LIGHTGRAY)
    g.gotoxy(13,22)
    g.write('Are you a ');g.col(WHITE,WHITE);g.write('N');g.col(YELLOW,LIGHTGRAY)
    g.write('ovice, an ');g.col(WHITE, WHITE);g.write('E');g.col(YELLOW, LIGHTGRAY)
    g.write('xperienced or an ');g.col(WHITE, WHITE);g.write('A');g.col(YELLOW, LIGHTGRAY)
    g.write('dvanced player?')
    g.col(LIGHTRED,BLACK);#g.write(chr(219)); # TODO the col() should flash
    g.bak(RED, LIGHTGRAY)
    #g.gotoxy(32,2);#g.col(randint(0, 16),0);write(' RETURN TO KROZ ');delay(50)
    g.flash(32, 2, ' RETURN TO KROZ ')

def main_menu(g: CellGrid):
    # bor(1)
    g.bak(BLACK, BLACK)
    g.clrscr()
    # cur(3)
    g.col(WHITE, LIGHTBLUE)
    g.gotoxy(33,2)
    g.write('RETURN TO KROZ')
    g.gotoxy(17,4)
    g.col(BROWN, LIGHTGRAY)
    g.write('Copyright (c) 1990 Apogee Software Productions')
    g.gotoxy(7,6)
    g.write('Version 1.2 -- Volume I of the Super Kroz Trilogy by Scott Miller')
    g.gotoxy(1,8)
    g.col(RED, LIGHTGRAY)
    # for x := 1 to 80 do write(#196)
    for _ in range(1, 80):
        g.write(chr(196))
    g.col(YELLOW,WHITE)
    g.gotoxy(28,12)
    g.write('B')
    g.col(COLORS[11],COLORS[7])
    g.write('egin your descent into Kroz...')
    g.col(COLORS[14],COLORS[15])
    g.gotoxy(28,14)
    g.write('I')
    g.col(COLORS[11],COLORS[7])
    g.write('nstructions')
    g.col(COLORS[14],COLORS[15])
    g.gotoxy(28,16)
    g.write('M')
    g.col(COLORS[11],COLORS[7])
    g.write('arketing Kroz')
    g.col(COLORS[14],COLORS[15])
    g.gotoxy(28,18)
    g.write('S')
    g.col(COLORS[11],COLORS[7])
    g.write('tory Behind Kroz')
    g.col(COLORS[14],COLORS[15])
    g.gotoxy(28,20)
    g.write('O')
    g.col(COLORS[11],COLORS[7])
    g.write('riginal Kroz Trilogy')
    g.gotoxy(27,23)
    g.col(COLORS[15],COLORS[0]);g.bak(BLUE, LIGHTGRAY)
    g.write('Your choice (B/I/M/S/O)? B'); #g.gotoxy(wherex-1,wherey); what is wherex wherey
    g.cur(2)
    # ClearKeys
    # read(kbd,ch)
    # if upcase(ch)='R' then MixUp:=true else MixUp:=false
    # ClearKeys
    # cur(3)


def instructions1(g: CellGrid):
    g.fill = BLUE
    g.bak(BLUE,BLACK)
    # g.bor(4)
    g.clrscr()
    # g.cur(3)
    # g.ClearKeys
    g.gotoxy(32,2);g.col(YELLOW,LIGHTGRAY);g.writeln('THE INSTRUCTIONS')
    g.gotoxy(32,3);          g.writeln('ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ')
    g.writeln()
    g.col(WHITE,LIGHTGRAY)
    g.writeln('   Return to Kroz is a game of exploration and survival.  Your journey will')
    g.writeln(' take you through 20 very dangerous chambers, each riddled with diabolical')
    g.writeln(' traps and hideous creatures.   Hidden in the deepest dungeon lies the')
    g.writeln(' priceless Crown of Kroz--your quest. Use the cursor pad to move 8 directions.')
    g.writeln('   The chambers contain dozens of treasures, spells, traps and other unknowns.')
    g.writeln(' Touching an object for the first time will reveal a little of its identity,')
    g.writeln(' but it will be left to you to decide how best to use it--or avoid it.')
    g.writeln('   When a creature touches you it will vanish, taking with it a few of your')
    g.writeln(' gems that you have collected. If you have no gems then the creature will')
    g.writeln(' instead take your life!  Whips can be used to kill nearby creatures, but')
    g.writeln(' they\'re better used to smash through "crumbled walls" and other terrain.')
    g.writeln('   PCjr players can use')
    g.writeln(' the alternate cursor                 U I O      ( NW N NE )')
    g.writeln(' pad instead of the cursor             J K       (   W E   )')
    g.writeln(' keys to move your man, and           N M ,      ( SW S SE )')
    g.writeln(' the four normal cursor keys.')
    g.writeln('   It\'s a good idea to save your game at every new level, therefore, if you die')
    g.writeln(' you can easily restore the game at that level and try again.')
    g.writeln('   Registered users can request a "Hidden Tricks and Hints" sheet if needed.')
    g.flash(27,25,'Press any key to continue.')
    g.bak(BLUE,BLACK)


def instructions2(g: CellGrid):
    g.fill = BLUE
    g.clrscr()
    # g.cur(3)
    # g.ClearKeys
    g.gotoxy(32,2);g.col(YELLOW,LIGHTGRAY);g.writeln('THE INSTRUCTIONS')
    g.gotoxy(32,3);          g.writeln('ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ')
    g.writeln()
    g.col(WHITE,LIGHTGRAY)
    g.writeln('   Return to Kroz will present you with many challenges.  You will venture deep')
    g.writeln(' underground and probably not make it out alive!')
    g.writeln()
    g.writeln(' Hints:  þ Use your player to touch each new object to find out about it.  When')
    g.writeln('           you first touch an object a message appears at the bottom of the')
    g.writeln('           screen that describes it.')
    g.writeln('       þþ> Don\'t forget to use the Home, End, PgUp, and PgDn keys to move your')
    g.writeln('           on-screen character diagonally (along with the marked cursor keys).')
    g.writeln('         þ Collect keys to unlock doors, which usually block the stairs going.')
    g.writeln('         þ The faster monsters are the most dangerous to touch--they will knock')
    g.writeln('           off three of your valuable gems.  The slowest creatures only take a')
    g.writeln('           single gem from you, and the medium speed monsters take two.')
    g.writeln('         þ Nearly every new level presents you with new objects to discover.')
    g.writeln()
    g.writeln('   To prove to you that this game CAN be completed, let me say (or brag) that I')
    g.writeln(' have finished this game on the "Advanced" skill level, with over 120 gems and')
    g.writeln(' 60 whips left to spare.  On the "Novice" level I can play and win one handed!')
    g.writeln('   There\'s many secret tricks in this game that can help you (even on Level 1)')
    g.writeln(' but even without these hidden maneuvers you can complete Return to Kroz.')
    g.flash(27,25,'Press any key to continue.')

def marketing(g: CellGrid):
    # g.bor(10)
    g.fill = BLUE
    g.bak(1,0)
    g.clrscr()
    # g.ClearKeys
    # g.cur(3)
    g.gotoxy(29,2);g.col(14,7);g.writeln('THE MARKETING OF KROZ')
    g.gotoxy(29,3);            g.writeln('ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ')
    g.writeln()
    g.col(15,7)
    g.writeln('   Return to Kroz is a user-supported game.  This means that the creator of')
    g.writeln(' this program relies on the appreciation of honest players to pay the game\'s')
    g.writeln(' minimal registration fee--$7.50.')
    g.writeln('   Payment of this fee entitles you to all the free help and hints you might')
    g.writeln(' need to enjoy the game.  All letters from registered users are answered')
    g.writeln(' within two days.  (Try to get this kind of support from commercial games!)')
    g.writeln('   Also, players can order the other Kroz sequels ONLY if this first')
    g.writeln(' registration fee is paid.  ($7.50 each or $20 for all three games.)')
    g.writeln('   Everyone who orders (or registers) all three of the Super Kroz Trilogy also')
    g.writeln(' get a "Hints, Tricks and Scoring Secrets" guide, and "The Domain of Kroz" map.')
    g.writeln('   A single Kroz games takes nearly six months to create, or, over 200 hours!')
    g.writeln(' I can\'t afford to devote this much time without receiving something in return.')
    g.writeln(' That is why I ask for this small fee, which is only necessary if you enjoy')
    g.writeln(' this game.  In other words, try before you buy.')
    g.writeln('   Even if you buy this game from a public domain or shareware library, I don\'t')
    g.writeln(' receive any of that money.  You\'re simply paying for "storage, distribution,')
    g.writeln(' disk, and handling".')
    g.writeln
    g.writeln('   -- Scott Miller, President, Apogee Software Productions')
    g.flash(27,25,'Press any key to continue.')

def story(g: CellGrid):
    g.fill = BLUE
    g.bak(1,0)
    g.clrscr()
    g.cur(3)
    g.gotoxy(29,2);g.col(14,7);g.writeln('THE STORY BEHIND KROZ')
    g.gotoxy(29,3);            g.writeln('ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ')
    g.writeln()
    g.col(15,7)
    g.writeln('   The original Kroz Trilogy (consisting of Caverns of Kroz, Dungeons of Kroz,')
    g.writeln(' and Kingdom of Kroz) was developed after I spent many hours playing another')
    g.writeln(' explore-the-levels type game titled Rogue.  I never could finish Rogue,')
    g.writeln(' though, because the game relied too much on luck and random occurrences.')
    g.writeln('   The name "Kroz" is actually Zork (an Infocom text adventure) spelled in')
    g.writeln(' reverse.  Many players still inquire about this bit of trivia.  The game was')
    g.writeln(' first designed without predefined level layouts, meaning every level was a')
    g.writeln(' random placement of creatures and play field objects.  New objects, like')
    g.writeln(' spells, lava, doors, etc., were added quickly as the first Kroz game took')
    g.writeln(' shape, including the ability to have predefined level floor plans.')
    g.writeln('   One of my objects was to create a game that wasn\'t all fast paced action,')
    g.writeln(' but also included strategy and puzzle solving.  Kingdom of Kroz was entered')
    g.writeln(' in a national programming contest in 1988 and took top honors in the game')
    g.writeln(' category, and number two overall (beat out by a spreadsheet program).')
    g.writeln('   The latest Kroz Trilogy has been greatly re-designed and re-programmed, but')
    g.writeln(' the familiar appearance has been mostly maintained.  You will discover new')
    g.writeln(' dangers, creatures and objects in your adventures below.  Good luck...')
    g.writeln('   The latest Kroz game, The Lost Adventures of Kroz, came about as a direct')
    g.writeln(' result of players requesting more, more, more Kroz!  So I delivered the goods.')
    g.flash(27,25,'Press any key to continue.')

    def tick():
        pass

    return tick
